# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "eutils"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joon Lee, aka seouri"]
  s.date = "2013-06-27"
  s.description = "Lightweight Ruby API for NCBI Eutils. This gem only provides API for NCBI Eutils. If you need full access to other NCBI databases, try BioRuby (bio gem) instead."
  s.email = "seouri@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "eutils.gemspec",
    "lib/eutils.rb",
    "test/helper.rb",
    "test/test_eutils.rb"
  ]
  s.homepage = "http://github.com/seouri/eutils"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Lightweight Ruby API for NCBI Eutils"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0"])
  end
end

